### ISSUE TITLE
an invalid line causes the next line to be skipped

### ISSUE THREAD

**Issue by akrantz01** [influxdata/line-protocol#43]
When parsing multiple lines of line protocol, if a line has a syntax error, the line immediately following it will be skipped. 

For example:
```
foo value=12.0
foo value=2a.0
foo value=32.0
foo value=42.0
```
This will successfully parse the first line, the second line will emit an error, but the third line will be skipped altogether, and finally, the fourth line will also be successfully parsed.

If you add two invalid lines back-to-back, an error will only be reported for the first invalid line. Example:
```
foo value=12.0
foo value=2a.0
foo value=8a.0
foo value=32.0
foo value=42.0
```

Here is the code I was using to test: https://gist.github.com/akrantz01/f047e400a586a7dfaf6006ca2876b7eb.

**Comment by rogpeppe** [comment]
Fixed by #45
